# serverless configuration

service: lloydant-lambda
app: lloydant-attendance
plugins:
    - serverless-offline
provider:
    apiGateway:
        binaryMediaTypes:
            - "*/*"
    name: aws
    runtime: nodejs10.x
functions:
    graphql:
        handler: main.handler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: true
            - http:
                  path: graphql
                  method: get
                  cors: true
